server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urldb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
