server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quartzdb
    username: postgres
    password: password
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 10000
